### ISSUE TITLE
Add TCP_NODELAY 

### ISSUE THREAD

**Issue by denyaalt** [jokester/publicaddr#17]
Hi,
Is it possible to add the TCP_NODELAY setting to SO_REUSEPORT to use them together?
Thanks.

**Comment by jokester** [comment]
Hi @denyaalt  . I didn't have a plan by far, because I don't know what it does.

Can you brief me about, in what case and why would people want it?

**Comment by denyaalt** [comment]
TCP_NODELAY disables the Nagle algorithm (disables buffering and delays), which allows data to be sent as quickly as possible.

**Comment by jokester** [comment]
@denyaalt Thanks for the explanation, didn't know that.

I did a research about `TCP_NODELAY` in nodejs. Maybe node.js already have that option around v18 as default in socket and http servers, via [PR](https://github.com/nodejs/node/pull/42163).

Sorry but can you check that too? (If node.js already have that capability I tend to not do it again)

**Comment by denyaalt** [comment]
Yes, this option is available in Node.js when we directly open a TCP socket, I'm not sure if it will work after your wrapper.
My colleague reported that when opening SO_REUSEPORT sockets from systemd, the TCP_NODELAY option does not work from Node.js, the user needs to additionally set the TCP_NODELAY flag in systemd.

**Comment by jokester** [comment]
@denyaalt that sounds more like a bug in node.js (unlike SO_REUSEPORT they decided to not support) 🤔 

Or, you are welcome to fork this repo and create a local build with `TCP_NODELAY` and see if it helps in your situation.

**Comment by denyaalt** [comment]
The absence of the SO_REUSEPORT flag is a big stupidity of the Node.js developers, it seems to me that they did not conduct tests.
Their solution of branching through the cluster module does not work under good load, the master passes all connections through itself and this is a bottleneck.
